[platformio]
src_dir = test

[env:head_arduino]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600

upload_port = COM3
monitor_port = COM3

[env:slave_one_arduino]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600

upload_port = COM4
monitor_port = COM4

[env:slave_two_arduino]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600

upload_port = COM5
monitor_port = COM5