[platformio]
src_dir = src

[env:head_arduino]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600

upload_port = COM3
monitor_port = COM3

[env:slave_one_arduino]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600

upload_port = COM4
monitor_port = COM4

[env:slave_two_arduino]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600

upload_port = COM5
monitor_port = COM5

[env:display_arduino]
platform = atmelavr
board = nanoatmega328
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L
upload_speed = 57600
framework = arduino
monitor_speed = 9600
upload_protocol = arduino

upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_src_filter = 
  -<*> 
  +<display.cpp>


lib_deps = 
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    Wire